# Change these first
owner: mrdavidkovacs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Asgard
    url: https://asgard.kovacs.pw
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: Jarvis
    url: https://jarvis.kovacs.pw
    icon: https://www.home-assistant.io/images/home-assistant-logo.svg
  - name: Matrix Chat Element UI
    url: https://chat.kovacs.pw
    icon: https://avatars.githubusercontent.com/u/8418310
  - name: Matrix Chat Synapse Server
    url: https://synapse.kovacs.pw
    icon: https://avatars.githubusercontent.com/u/8418310
  - name: Bitwarden
    url: https://pass.kovacs.pw
    icon: https://cdn.icon-icons.com/icons2/2108/PNG/512/bitwarden_icon_130977.png
  - name: Git
    url: https://git.kovacs.pw
    icon: https://gitea.io/images/gitea.png
  - name: Portainer
    url: https://containers.kovacs.pw
    icon: https://developer.asustor.com/uploadIcons/0020_999_1639454569_Portainer_ce_256.png
  - name: Time-Tracker
    url: https://time.kovacs.pw
    icon: https://raw.githubusercontent.com/traggo/logo/master/logo.png
  - name: Fss5Nas
    url: https://kovacs-fss5.quickconnect.to/
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
    __dangerous__body_down: "Cannot connect to"
  - name: ABB Backup
    check: "tcp-ping"
    url: backup.kovacs.pw
    port: 5510
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: ABB Restore
    url: https://backup.kovacs.pw
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg

assignees: # Users to assign downtime issues (optional)
  - mrdavidkovacs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kovacs.pw
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  theme: night
  introTitle: "Service Status Summary"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
